// Code generated by "stringer -type PgType ."; DO NOT EDIT

package pgclient

import "fmt"

const _PgType_name = "Bytea"

var _PgType_index = [...]uint8{0, 5}

func (i PgType) String() string {
	i -= 17
	if i < 0 || i >= PgType(len(_PgType_index)-1) {
		return fmt.Sprintf("PgType(%d)", i+17)
	}
	return _PgType_name[_PgType_index[i]:_PgType_index[i+1]]
}
