// Code generated by protoc-gen-go.
// source: transicator.proto
// DO NOT EDIT!

/*
Package common is a generated protocol buffer package.

It is generated from these files:
	transicator.proto

It has these top-level messages:
	ColumnPb
	ChangePb
*/
package common

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ColumnPb struct {
	Name             *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Value            *string `protobuf:"bytes,2,req,name=value" json:"value,omitempty"`
	Type             *int32  `protobuf:"varint,3,opt,name=type" json:"type,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ColumnPb) Reset()                    { *m = ColumnPb{} }
func (m *ColumnPb) String() string            { return proto.CompactTextString(m) }
func (*ColumnPb) ProtoMessage()               {}
func (*ColumnPb) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ColumnPb) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *ColumnPb) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

func (m *ColumnPb) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

type ChangePb struct {
	Operation        *int32      `protobuf:"varint,1,req,name=operation" json:"operation,omitempty"`
	Table            *string     `protobuf:"bytes,2,req,name=table" json:"table,omitempty"`
	Sequence         *string     `protobuf:"bytes,3,opt,name=sequence" json:"sequence,omitempty"`
	CommitSequence   *uint64     `protobuf:"varint,4,opt,name=commitSequence" json:"commitSequence,omitempty"`
	ChangeSequence   *uint64     `protobuf:"varint,5,opt,name=changeSequence" json:"changeSequence,omitempty"`
	CommitIndex      *uint32     `protobuf:"varint,6,opt,name=commitIndex" json:"commitIndex,omitempty"`
	TransactionID    *uint32     `protobuf:"varint,7,opt,name=transactionID" json:"transactionID,omitempty"`
	NewColumns       []*ColumnPb `protobuf:"bytes,8,rep,name=newColumns" json:"newColumns,omitempty"`
	OldColumns       []*ColumnPb `protobuf:"bytes,9,rep,name=oldColumns" json:"oldColumns,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *ChangePb) Reset()                    { *m = ChangePb{} }
func (m *ChangePb) String() string            { return proto.CompactTextString(m) }
func (*ChangePb) ProtoMessage()               {}
func (*ChangePb) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ChangePb) GetOperation() int32 {
	if m != nil && m.Operation != nil {
		return *m.Operation
	}
	return 0
}

func (m *ChangePb) GetTable() string {
	if m != nil && m.Table != nil {
		return *m.Table
	}
	return ""
}

func (m *ChangePb) GetSequence() string {
	if m != nil && m.Sequence != nil {
		return *m.Sequence
	}
	return ""
}

func (m *ChangePb) GetCommitSequence() uint64 {
	if m != nil && m.CommitSequence != nil {
		return *m.CommitSequence
	}
	return 0
}

func (m *ChangePb) GetChangeSequence() uint64 {
	if m != nil && m.ChangeSequence != nil {
		return *m.ChangeSequence
	}
	return 0
}

func (m *ChangePb) GetCommitIndex() uint32 {
	if m != nil && m.CommitIndex != nil {
		return *m.CommitIndex
	}
	return 0
}

func (m *ChangePb) GetTransactionID() uint32 {
	if m != nil && m.TransactionID != nil {
		return *m.TransactionID
	}
	return 0
}

func (m *ChangePb) GetNewColumns() []*ColumnPb {
	if m != nil {
		return m.NewColumns
	}
	return nil
}

func (m *ChangePb) GetOldColumns() []*ColumnPb {
	if m != nil {
		return m.OldColumns
	}
	return nil
}

func init() {
	proto.RegisterType((*ColumnPb)(nil), "common.ColumnPb")
	proto.RegisterType((*ChangePb)(nil), "common.ChangePb")
}

func init() { proto.RegisterFile("transicator.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 232 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x8f, 0x4d, 0x4e, 0xc3, 0x30,
	0x10, 0x85, 0x95, 0x36, 0x29, 0xc9, 0x94, 0xa0, 0xd6, 0x08, 0xe4, 0x65, 0x54, 0xb1, 0xc8, 0x2a,
	0x0b, 0x24, 0x4e, 0x00, 0x9b, 0xee, 0x90, 0x38, 0xc1, 0x34, 0x1d, 0x41, 0xa4, 0x64, 0x26, 0x38,
	0x0e, 0x3f, 0x17, 0xe6, 0x1c, 0x38, 0xb6, 0x92, 0x55, 0x97, 0xfe, 0xfc, 0xbe, 0x67, 0x3f, 0xd8,
	0x5b, 0x83, 0x3c, 0x34, 0x35, 0x5a, 0x31, 0x55, 0x6f, 0xc4, 0x8a, 0xda, 0xd4, 0xd2, 0x75, 0xc2,
	0x87, 0x27, 0x48, 0x9f, 0xa5, 0x1d, 0x3b, 0x7e, 0x3d, 0xa9, 0x6b, 0x88, 0x19, 0x3b, 0xd2, 0x51,
	0xb1, 0x2a, 0x33, 0x95, 0x43, 0xf2, 0x85, 0xed, 0x48, 0x7a, 0xe5, 0x8f, 0xee, 0xd2, 0xfe, 0xf6,
	0xa4, 0xd7, 0x45, 0x54, 0x26, 0x87, 0xbf, 0xc8, 0x79, 0x1f, 0xc8, 0xef, 0xe4, 0xbc, 0x3d, 0x64,
	0xd2, 0x93, 0x41, 0xdb, 0x08, 0x7b, 0x39, 0x99, 0x64, 0x8b, 0xa7, 0x76, 0x96, 0x77, 0x90, 0x0e,
	0xf4, 0x39, 0x12, 0xd7, 0xa1, 0x20, 0x53, 0xf7, 0x70, 0x33, 0xfd, 0xa0, 0xb1, 0x6f, 0x33, 0x8f,
	0x1d, 0x8f, 0x3d, 0xf7, 0xbd, 0x0b, 0x4f, 0x3c, 0xbf, 0x85, 0x6d, 0xc8, 0x1f, 0xf9, 0x4c, 0x3f,
	0x7a, 0xe3, 0x60, 0xae, 0xee, 0x20, 0xf7, 0xcb, 0xb0, 0x9e, 0x9e, 0x3e, 0xbe, 0xe8, 0x2b, 0x8f,
	0x1f, 0x00, 0x98, 0xbe, 0xc3, 0xac, 0x41, 0xa7, 0xc5, 0xba, 0xdc, 0x3e, 0xee, 0xaa, 0x30, 0xb8,
	0x5a, 0xd6, 0xba, 0x94, 0xb4, 0xe7, 0x39, 0x95, 0x5d, 0x4e, 0xfd, 0x07, 0x00, 0x00, 0xff, 0xff,
	0x2e, 0xd7, 0xa7, 0x28, 0x3b, 0x01, 0x00, 0x00,
}
